services:
  curriculum-service:
    build: .
    container_name: curriculum-service
    expose:
      - "8080"
    env_file:
      - .env.local
    networks:
      - lockdin-network
      - curr-sn
    depends_on:
      - curriculumDB

  curriculumDB:
    container_name: curriculum-db
    image: postgres:16-alpine
    command: -p 5433
    ports:
      - "5433:5433"
    env_file:
      - .env.local
    networks:
      - curr-sn
    volumes:
      - type: volume
        source: lockdin-storage
        target: /var/lib/postgresql/curriculum/data


volumes:
  lockdin-storage:

networks:
  curr-sn: