-- Add migration script here
INSERT INTO grades (id,
                    grade,
                    name,
                    display_order,
                    is_active)
VALUES (gen_random_uuid(),
        8,
        'Grade 8',
        0,
        false),
       (gen_random_uuid(),
        9,
        'Grade 9',
        1,
        false),
       (gen_random_uuid(),
        10,
        'Grade 10',
        2,
        false),
       (gen_random_uuid(),
        11,
        'Grade 11',
        3,
        false),
       (gen_random_uuid(),
        12,
        'Grade 12',
        4,
        false)
ON CONFLICT (grade) DO NOTHING;